### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by perdolka** [ogamespec/psxdev#44]
Извините, что так вторгаюсь.
Читал статью на Хабре о вас когда-то.
С приятным удивлением обнаружил, что вы не забросили это дело.
Реверс-инжиниринг процессора PlayStation 1 всё ещё в процессе? 
Насколько далеко удалось продвинутся (я читал, что у вас был перерыв в два года)?
Спрашиваю, потому что увидел в новостях на сайте, что вы также переключились на GPU и микросхемы привода.

**Comment by ogamespec** [comment]
Привет, ув. perdolka :)
Да, прогресс идёт медленно и спорадически =) В данный момент в сторону машинного обучения и автоматизации процесса получения изображений.
Вы можете посмотреть прогресс по текущим проектам в этой репе.

**Comment by perdolka** [comment]
Спасибо за ответ. :)
Жаль, моего скила недостаточно чтобы вам помочь.
Осмелюсь только посоветовать написать на хабре статью о том, как машинное обучение помогает с автоматизацией этого процесса - для привлечения внимания к теме и, возможно, привлечения новых людей.
Удачи вам.
